server:
  port: 8083

spring:
  datasource:
    username: root
    password: '050596'
    url: jdbc:mysql://localhost:3306/my-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    password: 123456
    host: 192.168.37.128
    port: 6379