server:
  port: 8084

spring:
  application:
    name: gateway
  redis:
    timeout: 2000 # 连接或读取超时时长（毫秒）
    database: 7
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
    host: 192.168.37.128
    password: 123456
  redisson:
    address: redis://192.168.37.128:6379
    database: 7
    password: 123456
  main:
    allow-bean-definition-overriding: true