server:
  port: 8082

spring:
  datasource:
    username: root
    password: '050596'
    url: jdbc:mysql://localhost:3306/my-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver